apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-classifier
  labels:
    app: traffic-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-classifier
  template:
    metadata:
      labels:
        app: traffic-classifier
    spec:
      containers:
        - name: traffic-classifier
          image: mlops-pipeline:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
